name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: ruff_check
        run: ruff format .
      - name: ruff format
        run: ruff format . --check
  
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: yezz123/setup-uv@v4
      - run: uv --version
      - run: python -m uv pip install --no-cache -r requirements.txt
      - run: pytest tests -vv -ss